install:
- npm install
branches:
  only:
  - master
language: node_js
sudo: false
node_js: stable
cache:
  directories:
  - node_modules
before_script:
- git pull origin master

before_install:
- openssl aes-256-cbc -K $encrypted_517b46f21074_key -iv $encrypted_517b46f21074_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 118.24.62.205\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
- npm test
after_success:
- npm run build
- scp stricthostkeychecking=no dist/* root@118.24.62.205:/home/test/cherryblog.site

env:
  global:
  - GH_REF: github.com/sunshine940326/blog_management.git