branches:
  only:
    - master

language: node_js

node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

after_success:
  - npm run build
  - cd dist
  - cp index.html 404.html
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet --force  "https://${github_setting}@${GH_REF}" master:master

# Note: you should set Environment Variables here or 'Settings' on travis-ci.org
env:
  global:
    - GH_REF: github.com/sunshine940326/blog_management.git